# Generated by Django 5.0.2 on 2025-05-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='cupos_disponibles',
            field=models.IntegerField(),
        ),
    ]
