# Generated by Django 5.0.2 on 2025-05-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_clase_cupos_disponibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='cupos_disponibles',
            field=models.IntegerField(default=0),
        ),
    ]
