# Generated by Django 5.0.2 on 2025-05-23 05:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_clase_cupos_disponibles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clase',
            options={'ordering': ['horario'], 'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_reserva'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AddField(
            model_name='clase',
            name='instructor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='clase',
            name='sala',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sala/Lugar'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='cupos_disponibles',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cupos disponibles'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='horario',
            field=models.DateTimeField(verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la clase'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.clase', verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
